spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/quotewall

spring.datasource.username=quotewall
spring.datasource.password=quotewall

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.open-in-view=false